INSERT INTO emp(gender, hire_date, emp_id, created_date, last_login, photo_file_id, post_code, status, rrn, mobile, role_code, emp_name, email, address1, address2, emp_pwd) VALUES (
	'M', '25/11/09', '2511301', '25/11/10 11:16:22.030042000', '', '', '28562', 'ACTIVE', '', '010-1234-2222', 'USER', '홍길동', 'hong@hong.com', '광주 동구 2순환로 575 (지산동)', '2', '$2a$10$j1X19qACsW1Yh0F0gG4meu.JMoxuTjZf46xW.i4aC2NkfvyWyM7v6'
);

-- 부서 DEPT
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP000', 'ERP본부', NULL, NULL, 'Y', SYSDATE, 'ERP');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP100', 'MES본부', NULL, NULL, 'Y', SYSDATE, 'MES');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP001', '개발부', 'DEP000', NULL, 'Y', SYSDATE, 'DEV');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP002', '마케팅부', 'DEP000', NULL, 'Y', SYSDATE, 'MKT');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP003', '생산부', 'DEP000', NULL, 'Y', SYSDATE, 'PRD');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP004', '영업부', 'DEP000', NULL, 'Y', SYSDATE, 'SAL');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP005', '인사부', 'DEP000', NULL, 'Y', SYSDATE, 'HR');

-- 직급 POSITION
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS001', '사원', 1, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS002', '대리', 2, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS003', '과장', 3, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS004', '차장', 4, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS005', '부장', 5, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS006', '이사', 6, 'Y', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS007', '사장', 7, 'Y', 'Y', SYSDATE);

-- 역할 ROLE
INSERT INTO ROLE (ROLE_CODE, ROLE_NAME, ROLE_DESC, USE_YN, CREATED_DATE)
VALUES ('ROLE_ADMIN',     '전체 관리자', '시스템 전역 접근 가능(임원/관리자)', 'Y', SYSDATE);
INSERT INTO ROLE (ROLE_CODE, ROLE_NAME, ROLE_DESC, USE_YN, CREATED_DATE)
VALUES ('ROLE_ADMIN_SUB', '부서 관리자', '부서 단위 관리 권한(자동 부서장)', 'Y', SYSDATE);