-- 부서 DEPT
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP000', 'ERP본부', NULL, NULL, 'Y', SYSDATE, 'ERP');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP100', 'MES본부', NULL, NULL, 'Y', SYSDATE, 'MES');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP001', '개발부', 'DEP000', NULL, 'Y', SYSDATE, 'DEV');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP002', '마케팅부', 'DEP000', NULL, 'Y', SYSDATE, 'MKT');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP003', '생산부', 'DEP000', NULL, 'Y', SYSDATE, 'PRD');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP004', '영업부', 'DEP000', NULL, 'Y', SYSDATE, 'SAL');
INSERT INTO DEPT (DEPT_ID, DEPT_NAME, PARENT_ID, HEAD_EMP_ID, USE_YN, CREATED_DATE, DEPT_ABBR)
VALUES ('DEP005', '인사부', 'DEP000', NULL, 'Y', SYSDATE, 'HR');

-- 직급 POSITION
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS001', '사원', 1, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS002', '대리', 2, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS003', '과장', 3, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS004', '차장', 4, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS005', '부장', 5, 'N', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS006', '이사', 6, 'Y', 'Y', SYSDATE);
INSERT INTO POSITION (POS_CODE, POS_NAME, RANK_ORDER, IS_EXECUTIVE, USE_YN, CREATED_DATE)
VALUES ('POS007', '사장', 7, 'Y', 'Y', SYSDATE);

-- 역할 ROLE
INSERT INTO ROLE (ROLE_CODE, ROLE_NAME, ROLE_DESC, USE_YN, CREATED_DATE)
VALUES ('ROLE_ADMIN',     '전체 관리자', '시스템 전역 접근 가능(임원/관리자)', 'Y', SYSDATE);
INSERT INTO ROLE (ROLE_CODE, ROLE_NAME, ROLE_DESC, USE_YN, CREATED_DATE)
VALUES ('ROLE_ADMIN_SUB', '부서 관리자', '부서 단위 관리 권한(자동 부서장)', 'Y', SYSDATE);

-- 근무 정책
INSERT INTO work_policy (id, in_time, out_time, lunch_in, lunch_out, late_limit, annual_basis, created_date) 
VALUES (1, '09:00', '18:00', '12:00', '13:00', 5, 'FY', SYSDATE);

-- 공통 코드 연차 기준
INSERT INTO COMMON_CODE (
    CODE_ID, CODE_NAME, CODE_SEQ, CODE_DESC, LEVEL_NO, USE_YN, SYS_TYPE, CREATED_USER, CREATED_DATE
) VALUES (
    'ANNUAL_BASIS', '연차 기준', 1, '연차 산정 기준 구분 그룹', 1, 'Y', 'COMMON', 'SYSTEM', SYSDATE
);

INSERT INTO COMMON_CODE (
    CODE_ID, PARENT_CODE_ID, CODE_NAME, CODE_SEQ, CODE_DESC, LEVEL_NO, USE_YN, SYS_TYPE, CREATED_USER, CREATED_DATE
) VALUES (
    'FY', 'ANNUAL_BASIS', '회계연도 기준', 1, '회계연도를 기준으로 연차를 산정', 2, 'Y', 'COMMON', 'SYSTEM', SYSDATE
);

INSERT INTO COMMON_CODE (
    CODE_ID, PARENT_CODE_ID, CODE_NAME, CODE_SEQ, CODE_DESC, LEVEL_NO, USE_YN, SYS_TYPE, CREATED_USER, CREATED_DATE
) VALUES (
    'JOIN', 'ANNUAL_BASIS', '입사일 기준', 2, '입사일을 기준으로 연차를 산정', 2, 'Y', 'COMMON', 'SYSTEM', SYSDATE
);